run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  goimports:
    local-prefixes: image-api

issues:
  exclude-rules:
    - path: internal/api/api.gen.go
      linters:
        - errcheck
        - govet
        - staticcheck
        - unused
